# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [23]:
# import NumPy into Python
import numpy as np


# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001, size=(1000,20))

# print the shape of X
print(X)


[[2780  558 1639 ...  253 3536  806]
 [3947 1689 2189 ... 4455 3068 1766]
 [ 911 2341 1364 ... 1565 3959 1093]
 ...
 [4880 4050 3474 ... 4520 2041  309]
 [2427 2308 1001 ... 3535 3072  688]
 [1774  241 4136 ...  193 1320 3024]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [20]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [27]:
# Print the shape of ave_cols
print(ave_cols.shape)


# Print the shape of std_cols
print(std_cols.shape)



(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [28]:
# Mean normalize X
X_norm = (X-ave_cols)/std_cols

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [38]:
# # Print the average of all the values of X_norm
# print(X_norm.mean())


# # Print the average of the minimum value in each column of X_norm
# print(X_norm.mean(axis=0).min())


# Print the average of the maximum value in each column of X_norm
print(X_norm.mean(axis=0).max)


0.01363401581512552
-0.03651740150317353
0.11440547011609128


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [47]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])

[832 300 410 304 202 645 795 274 930 226 846 167 239 914  59 942  95 484
 950 526 498 687 530 509 351 837 267 149 842 139 313 581 702 533   3 541
 946 807 450  38 726 988 195 121 691 909 894 635 340 841 373 684 265 763
 893 993 296 176 804 955 443 454 416 845 905 618 129 891 433 507 377 113
 515 862 278 979 548 882 103  12 912 228 782  27 428 574 193  64 705 473
 639 727 714 822 282 551 688 939 209 158 713  88 579 562 136 186 965 414
 232 570 722 479 883 221 741 774 809  33 248 583 928 500 447 405 601 438
 319 275 423 557  37 118 598 831  57  46 758 651 686 483 393 397 696  19
 678 952 204 597  40 307 730 543 192 791 437  70 549 823 870 720 875 703
  84 126 398 615 153 641 162 577 830  73 889 518  22 522 789 528 649 712
 128 145  74 317 816 652 906  85 259 254 931 732 117 948 244 724 706 346
 568  55 986 821 375 658 429 974  24 588  36 107 512 442 637  76 941 867
  80 833 944 838 342 787 144 417 499 987 470 753 323 576 390 735 879 173
 237 911 172 591 602 331 638 130 693 755 779 471 52

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [58]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.


# Create a Training Set
X_train = X_norm[row_indices[:600]]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[600:800]] 

# # Create a Test Set
X_test = X_norm[row_indices[800:]]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [60]:
# Print the shape of X_train
print(X_train.shape)


# Print the shape of X_crossVal
print(X_crossVal.shape)


# Print the shape of X_test
print(X_test.shape)


(600, 20)
(200, 20)
(200, 20)
